tasks:
  - name: try
    command: gp preview $(gp url 3306)index.php

image:
  file: .gitpod.Dockerfile

ports:
  - port: 3300
    onOpen: open-preview

vscode:
  extensions:
    - felixfbecker.php-debug@1.13.0