image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: ignore

tasks:
  - init: composer update
    command: php -S 0.0.0.0:8000 -t public/

vscode:
  extensions:
    - felixfbecker.php-debug@1.13.0